name: Dynawo master

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Pre-requisites
        run: pip install lxml psutil

      - name: Install
        run: |
          ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          git clone https://github.com/dynawo/dynawo.git
          cd dynawo
          git checkout 1157_fix_macos
          curl -L https://github.com/gautierbureau/dynawo-macos-omc/releases/download/test/Dynawo-OpenModelica-MacOS.zip -o Dynawo-OpenModelica-MacOS.zip
          unzip Dynawo-OpenModelica-MacOS.zip
          export DYNAWO_HOME=$(pwd)
          export DYNAWO_SRC_OPENMODELICA=$DYNAWO_HOME/OpenModelica-Source
          export DYNAWO_INSTALL_OPENMODELICA=$DYNAWO_HOME/OpenModelica
          export DYNAWO_LOCALE=en_GB
          export DYNAWO_NB_PROCESSORS_USED=1
          export DYNAWO_BUILD_TYPE=Debug
          export DYNAWO_CXX11_ENABLED=NO
          export DYNAWO_COMPILER=CLANG
          export DYNAWO_RESULTS_SHOW=false
          # export VERBOSE=1
          #sed -i '' 's/-DCMAKE_SKIP_BUILD_RPATH=True//' dynawo/sources/ModelicaCompiler/DYNCompileModelicaModel.cpp
          #sed -i '' '61d' dynawo/sources/Simulation/CMakeLists.txt
          #sed -i '' '36a\
          #libZIP::libZIP' dynawo/sources/Simulation/CMakeLists.txt
          #cat dynawo/sources/Simulation/CMakeLists.txt
          #cat dynawo/sources/Launcher/CMakeLists.txt
          ./util/envDynawo.sh build-user
          # cat /Users/runner/work/dynawo-test/dynawo-test/dynawo/build/clang11.0.3/master/Debug-cxx11/shared/dynawo/sources/Models/Modelica/P/EventQuadripoleConnection.log
          # echo
          # cat /Users/runner/work/dynawo-test/dynawo-test/dynawo/build/clang11.0.3/master/Debug-cxx11/shared/dynawo/sources/Models/Modelica/P/EventQuadripoleConnection/CMakeFiles/lib.dir/link.txt
          # echo
          # otool -L /Users/runner/work/dynawo-test/dynawo-test/dynawo/build/clang11.0.3/master/Debug-cxx11/shared/dynawo/sources/Models/Modelica/P/EventQuadripoleConnection/EventQuadripoleConnection.dylib
          # echo
          # otool -l /Users/runner/work/dynawo-test/dynawo-test/dynawo/build/clang11.0.3/master/Debug-cxx11/shared/dynawo/sources/Models/Modelica/P/EventQuadripoleConnection/EventQuadripoleConnection.dylib
          # echo
          # otool -L /Users/runner/work/dynawo-test/dynawo-test/dynawo/install/3rdParty/clang11.0.3/shared/Debug-cxx11/adept/lib/libadept.dylib
          # echo
          # otool -l /Users/runner/work/dynawo-test/dynawo-test/dynawo/install/3rdParty/clang11.0.3/shared/Debug-cxx11/adept/lib/libadept.dylib
          # exit 1
          #./util/envDynawo.sh build-tests
          #./util/envDynawo.sh nrt
          otool -L /Users/runner/work/dynawo-test/dynawo-test/dynawo/install/clang11.0.3/master/Debug-cxx11/shared/dynawo/bin/dynawo
          ./util/envDynawo.sh distrib-omc
          version=$(./util/envDynawo.sh version | cut -f1 -d' ')
          asset_id=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-test/releases/tags/test | grep -B 2 -m 1 Dynawo_MacOS_master.zip | grep '"id"' | awk '{print $2}' | tr -d ',')
          [ ! -z "$asset_id" ] && curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/gautierbureau/dynawo-test/releases/assets/${asset_id}
          upload_url=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-test/releases/tags/test | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/zip' -X POST  ${upload_url}?name=Dynawo_MacOS_master.zip --data-binary @distributions/Dynawo_omc_V${version}.zip
