name: Dynawo master

on: [push]

defaults:
  run:
    shell: bash
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Pre-requisites
        run: pip install lxml psutil

      - name: Install
        run: |
          git clone https://github.com/dynawo/dynawo.git
          cd dynawo
          curl -L https://github.com/gautierbureau/dynawo-macos-omc/releases/download/test/Dynawo-OpenModelica-MacOS.zip -o Dynawo-OpenModelica-MacOS.zip
          unzip Dynawo-OpenModelica-MacOS.zip
          export DYNAWO_HOME=$(pwd)
          export DYNAWO_SRC_OPENMODELICA=$DYNAWO_HOME/OpenModelica-Source
          export DYNAWO_INSTALL_OPENMODELICA=$DYNAWO_HOME/OpenModelica
          export DYNAWO_LOCALE=en_GB
          export DYNAWO_NB_PROCESSORS_USED=4
          export DYNAWO_BUILD_TYPE=Debug
          export DYNAWO_CXX11_ENABLED=YES
          export DYNAWO_COMPILER=CLANG
          export DYNAWO_RESULTS_SHOW=false
          ./util/envDynawo.sh build-user
          ./util/envDynawo.sh build-tests
          ./util/envDynawo.sh nrt
          ./util/envDynawo.sh distrib-omc
          version=$(./util/envDynawo.sh version | cut -f1 -d' ')
          asset_id=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-test/releases/tags/test | grep -B 2 -m 1 Dynawo_MacOS_master.zip | grep '"id"' | awk '{print $2}' | tr -d ',')
          [ ! -z "$asset_id" ] && curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -X DELETE https://api.github.com/repos/gautierbureau/dynawo-test/releases/assets/${asset_id}
          upload_url=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --request GET https://api.github.com/repos/gautierbureau/dynawo-test/releases/tags/test | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
          curl -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H 'Content-Type: application/zip' -X POST  ${upload_url}?name=Dynawo_MacOS_master.zip --data-binary @distributions/Dynawo_omc_V${version}.zip
